version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongo_container"
    ports:
      - 27017:27017
  springboot:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: "springboot_container"
   ports:
    - 8080:8080
   depends_on:
    - mongodb
    